// v6.7.1937
(function(u,n,J,B,D,x,ea,p){function v(a,c,b){return function(){a(c,b)}}function F(a){return"object"==typeof a}function va(){for(var a=32,c="";a--;)c+=(0|16*Math.random()).toString(16);return c}function G(a,c,b,d,e){(e=a.addEventListener)?e.call(a,c,b,!1):a.attachEvent(d||"on"+c,b)}function fa(){return J&&"preview"==J.loadPurpose}function K(a,c){for(var b in a)a.hasOwnProperty(b)&&a[b]!==p&&c(a[b],b)}function L(a,c){var b=[];K(a,function(d,e){var f=b.push,g=ea(e)+"=";if(c){var h=(typeof d).charAt(0);
h=("[object Array]"==X.call(d)?"a":"[object Date]"==X.call(d)?"d":h)+("[object Date]"==X.call(d)?+d:F(d)&&d?L(d,c):d)}else h=d;f.call(b,g+ea(h))});return b.join("&")}function M(a,c){if(!a)throw Error(c);}function wa(a){S[ha]=a;return ha++}function H(a,c,b,d,e){c?a(T(c),b,d,e):K(w,function(f){a(f,b,d,e)})}function ia(a){a=new x(a);return"expires="+a.toGMTString()+";"}function U(a,c){var b="path=/;",d=a.g(6);d&&(b+="domain="+d+";");"https:"==location.protocol&&(b+="secure");return{u:function(e,f){a.g(1,
!0)&&(n.cookie=e+"="+f+";"+ia(+new x+(c?6E10:6E4))+b)},B:function(e){if(a.g(1,!0))return(n.cookie.match("(^|;)\\s*"+e+"=([^;]*)")||[])[2]||p},da:function(e){n.cookie=e+"=;"+ia(0)+b}}}function Y(){function a(f){return u["inner"+f]||b&&b[e="client"+f]||d&&d[e]}function c(f){return Math.max(d[e="scroll"+f]|0,b[e]|0,d[e="offset"+f]|0,b[e]|0,d[e="client"+f]|0,b[e]|0)}var b=n.documentElement,d=n.body||b,e;return{aa:a("Width"),$:a("Height"),T:c("Width"),S:c("Height"),D:u.pageXOffset||b&&b.scrollLeft||0,
F:u.pageYOffset||b&&b.scrollTop||0}}function ja(a){a.m&&(a.m=!1,a.A=new x-a.I+(a.A||0))}function Z(a){D(a.ka);a.ka=B(v(ja,a),15E3);a.m||(a.m=!0,a.I=new x)}function xa(a){var c=a.A,b=new x;a.m&&(c+=b-a.I,a.I=b);a.A=0;return c}function ya(a){Z(a);var c=Y();c.F>a.K&&(a.K=c.F);c.D>a.J&&(a.J=c.D)}function za(a){var c=v(Z,a);G(n,"mousemove",c);G(n,"keydown",c);G(u,"scroll",v(ya,a));G(n,"focus",c,"focusin");G(n,"blur",v(ja,a),"focusout")}function ka(a,c){var b=n.getElementsByTagName("head")[0],d=n.createElement("script"),
e=+new x;d.onerror=function(){100>+new x-e&&c&&c()};d.src=a;b.appendChild(d);return function(){d&&b.removeChild(d);d=null}}function N(a,c,b,d,e,f){var g=v,h=B(function(){g();aa=(aa+1)%ba.length;b.et&&(b.et=0);b.rt=1;--e&&N(a,c,b,d,e,f)},5E3),k=I(a);b.cb=wa(function(l,m,y){g();D(h);d(l,m,y)});b.a=a.h;b.au=k.P;b.id=k.j;b.cid=k.G;b.tv="6.7.1937";k=c+"?"+L(b);g=ka((Aa?"http":"https")+"://"+("chat"==c?c:ba[aa])+".gosquared.com/"+k,f)}function V(a,c,b,d){if(a.i!==p){if(!b){var e=Y();b={vw:e.aa,vh:e.$,dw:e.T,
dh:e.S,st:e.D,sl:e.F,mst:a.K,msl:a.J}}b.i=a.i;b.e=c;b.et=xa(a);z&&(b.bc=1);a.fa&&(b.rc=1);N(a,"ping",b,function(f){d&&d();null!==f&&(D(a.o),a.o=B(v(V,a),[7E3,12E3][a.oa++]||17500+5E3*Math.random()),f&&E(["c",a.h]))},5)}else B(function(){V(a,c,b,d)},5E3)}function W(a,c,b,d){M(c,"Event name is required");b&&b.call&&(d=b,b=p);if(b===""+b||b===+b)b={caption:b};c={gs_evt_name:c,d:L(b||{},!0)};V(a,"event",c,d)}function Ba(a,c,b,d){function e(l,m){m=m||(F(l)?l:{});F(l)||(m.name=l);M(m.name,"No Name");h.push(m);
return k}function f(l){for(var m=0;m<l.length;)e(l[m++]);return k}function g(){H(function(l){var m=U(l,1),y="gs_t_"+l.h,q=m.B(y)||0;m.u(y,+new x);W(l,"_transaction",{id:c,pt:{ts:+q},i:h,d:b})},a)}!b&&F(c)&&(b=c,c=b.id);var h=[],k;d&&f(d);b&&b.track&&g();return k={id:c,addItem:e,addItems:f,track:g}}function Ca(a){var c=n.createElement("a");c.href=a||u.location.href;return c.href}function la(a,c,b){c=Ca(c);a.g(7,!0)||(c=c.replace(/\?([^#]*)/,function(d,e){e=e.split("&");for(var f=[],g=0;g<e.length;g++)/^utm_/.test(e[g])&&
f.push(e[g]);return f.length?"?"+f.join("&"):""}));a.g(8)||(c=c.replace(/#.*$/,""));return{na:c,ma:b!==p?b:n.title,X:/^file:/.test(c)||/\/\/localhost[\/:]/.test(c+"/"),W:/fb_xd_(bust|fragment)/.test(c)}}function Da(a){a=a.g(10,n.referrer);var c;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":c=a.replace(/^.*?\/\//,"").indexOf(location.host);return{V:+(0<=c&&8>=c),ra:a}}function Ea(){var a=0,c=0;screen&&(a=screen.width,c=screen.height);var b=(b=u.orientation)&&(b+360)%180;return{N:b?
c:a,M:b?a:c,va:screen&&screen.colorDepth||"-",ca:J.language||J.browserLanguage||"-",ea:n.characterSet||n.charSet||"-",pa:u.devicePixelRatio||1,xa:J.maxTouchPoints||0,ja:(new x).getTimezoneOffset()}}function O(a){function c(){var g=d.name;g&&(d.name=g.split(":_GS_:")[0])}var b;if(O[a])return O[a];var d=u.top;O[a]=b=function(){c();d.name=(d.name||"")+":_GS_:"+[a,b.j,b.L]};try{var e=d.name||"";if(-1!=e.indexOf(":_GS_:")){var f=e.split(":_GS_:")[1].split(",");f[0]==a&&(b.j=f[1]||"",b.L=f[2]||"")}c()}catch(g){d=
{}}return b}function Fa(a){if(a.i!==p){var c=U(a);a.g(1,!0)?c.u("gs_p_"+a.h,a.i):(c=O(a.h),c.L=a.i,c())}}function Ga(a,c){function b(){"event"===e&&W(c,f.name,f.data);"chat"===e&&E(["show",f.message])}for(var d=a[1],e=a[2],f=a[3],g=n.querySelectorAll(a[0]),h=0;h<g.length;h++)g[h].addEventListener(d,b)}function ca(a,c,b,d){c&&c.call&&(d=c,c=p);b&&b.call&&(d=b,b=p);b=la(a,c,b);var e=Da(a),f=a.i===p&&!e.V,g=a.O=I(a),h=Ea(),k=Y(),l=a.g(5);g.ga(1,f);D(a.o);a.A=0;a.m=!1;Z(a);if(!(!a.g(9)&&b.X||b.W||fa()||
h.N&&h.M&&10>h.N&&10>h.M)){a.K=k.za;a.J=k.ya;var m={cs:h.ea,cd:h.va,la:h.ca,sw:h.N,sh:h.M,dp:h.pa,tp:h.xa,pu:b.na,pt:b.ma||"-",ri:e.V,ru:e.ra,re:+g.ta,vi:g.H,pv:g.C,lv:g.ia,vw:k.aa,vh:k.$,dw:k.T,dh:k.S,st:k.F,sl:k.D,un:a.g(3),pp:g.qa(),ec:l,aip:a.g(2)?1:p,tz:h.ja};a.l&&(m.cp=L(a.l,!0));a.sa||!1===a.g(15)||(m.rc=1,a.sa=!0);z&&(a.uid=g.j,m.bc=1);a.oa=0;var y;N(a,"pv",m,function(q,C,t){q!==p&&(a.i=q,D(a.o),a.o=B(v(V,a),5E3),d&&d());C&&!y&&(ma(a,C),a.fa=!0);if(t)for(q=0;q<t.length;q++)Ga(t[q],a)},5,function(){m.rc&&
!y&&(y=1,Ha(a))});a.i!==p?c!==p&&(a.i=p):(B(v(za,a),500),G(u,"beforeunload",v(Fa,a)))}}function Ia(a,c,b){!b&&F(c)&&(b=c,c=b.id,!c&&b.email&&(c="email:"+b.email));M(c,"ID or email required");"__n/v_"!==c&&a.s(13,c);b&&a.s(4,b)}function A(a,c,b,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))c!==""+c&&(b=c,c=0),da(a,c,b||b===p);else if(S[a])S[a](c,b,d),delete S[a];else{var e=function(g,h,k){f?T(f).s(g,h,k):K(w,function(l){l.s(g,h,k)})};a=a.split(".");var f;1<a.length&&(f=a.shift());a=a[0];if(/transaction$/i.test(a))return Ba(f,
c,b,d);if("get"==a)return b=na[(c+"").toLowerCase()]||c,f?d=T(f).g(b):K(w,function(g){d=g.g(b)}),d;"set"==a?(a=(c+"").split("."),c=a.shift(),e(na[c.toLowerCase()]||c,b,a.join("."))):"track"==a?H(ca,f,c,b,d):"event"==a?H(W,f,c,b,d):"cancel"==a?H(function(g){g.R()},f):"noCookies"==a?e(1,!1):"anonymizeIP"==a?e(2,!0):"tag"==a?e(3,c):"load"==a?c&&c():"auth"==a?e(14,c):"identify"==a?H(Ia,f,c,b,d):"alias"==a?e(13,c):"unidentify"==a?H(function(g){if(g.g(13)||E(["e",g.h]))g.s(13),I(g).ua(1)}):"props"==a||
"properties"==a?e(4,c):"chat"==a&&E([c,b,d])}}function E(a){var c=A.c;c||(c=A.c=function(b){c.q.push(b)},c.q=[]);return c(a)}function ma(a,c){E(c);var b=A.c;b.c||(b.c=[2,a.h,a.g(15),a.g(11),a.g(6)]);var d="https://js.gs-chat.com/chat",e=(b=c[0])&&b.channel;e&&(d+="-"+e);d=(a.g(15)||{}).js||d+".js";oa||(oa=!0,ka(d+(b?"?"+b.v:"")))}function Ha(a){N(a,"chat",{},function(c){c&&(c[0]&&(c[0].notrack=1),ma(a,c))})}function I(a){function c(r){f.u(d,g.j=r?"":[l,548*t.H+2019,379*t.C+4621,+new x].join(":"));
a.s(11,r?0:l)}function b(r){q&&"-"!==q?(f.u(e,q+(C?"|"+C:"")),E(["i",a.h,q,C,r])):(f.u(e,""),E(["u",a.h,r]))}var d="gs_u_"+a.h,e="gs_v_"+a.h,f=U(a,1),g=O(a.h),h=(f.B(d)||g.j||"").split(/(?::|%3A)/),k=!0,l=a.g(11,h[0])||(k=!1,va()),m=((h[1]||2019)-2019)/548,y=((h[2]||4621)-4621)/379;h=(h[3]||0)/1E3;var q=a.g(13),C=a.g(14);var t={j:l,G:q,H:m,C:y,ia:~~h,ta:k,ga:function(r,Ja){t.C+=+r;t.H+=+Ja;c()},Z:function(r){q=t.G=r;b(1)},ua:c,qa:function(){var r=f.B("gs_p_"+a.h)||g.L;f.da("gs_p_"+a.h);return a.i!==
p?a.i:r},P:C,wa:function(r){M(/^[0-9a-f]{64}$/.test(r),"Invalid auth signature");C=t.P=r;b(1)}};b();return t}function pa(a){if(a.O){var c=la(a);!a.g(9)&&c.X||c.W||fa()||(c=L(a.l,!0))&&N(a,"prop",{cp:c},v,5)}else B(function(){pa(a)},100)}function qa(a,c,b){var d=a.l=a.l||{};M(c||F(b),"Not an object");c?d[c]=b:d=a.l=b;!a.Y&&a.O&&(a.Y=B(function(){pa(a);a.Y=0},5))}function ra(a){var c="gs_v_"+a,b=this,d=[];d[12]=b.h=a;b.s=function(f,g,h){4==f&&(qa(b,h,g),g&&!b.U&&(h=g.id,g=g.email,!h&&g&&(h="email:"+
g),h&&(b.U=h,I(b).Z(h))),g=b.l);13==f&&(qa(b,"id",g),g=(b.U=g)||"-",I(b).Z(g));14==f&&I(b).wa(g);d[f]=g};b.g=function(f,g){function h(){var k=U(b,1).B(c);if(/\|[0-9a-f]{32,64}/.test(k)){k=k.split("|");var l=k.pop();k=k.join("|")}return{ba:l,G:k}}return f in d?d[f]:13===f?h().G||g:14===f?h().ba||g:g};var e;b.ha=function(){e=B(v(ca,b),20)};b.R=function(){D(b.o);D(e)}}function da(a,c,b){if(!a)for(a in w)return w[a];if(w[c||a])return w[c||a];a=w[c||a]=new ra(a);b&&a.ha();return a}function T(a){var c=
w[a];if(c)return c;for(var b in w)if(w[b].h==a)return w[b]}function sa(a){return function(c,b,d){a(this,c,b,d)}}function Ka(){if(z){var a=ra.prototype;a.TrackView=sa(ca);a.TrackEvent=sa(W);a.Cancel=function(){this.R()};z.Tracker=da;z.Cancel=v(A,"cancel");K(z,function(c,b){"acct"==b?(da(c,"_default",!0),A(function(){function d(f){e[f.shift()].apply(e,f)}var e=z.DefaultTracker=T("_default");if(b=z.q)for(;c=b.shift();)d(c);z.q={push:d};(b=z.load)&&b(e)})):"load"!=b&&"q"!=b&&A("set",b,c)})}}var X=Object.prototype.toString,
S={},ha=0,ba=["data","data2"],aa=0|Math.random()*ba.length,Aa=/^http:/.test(location.href),na={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4,chat:15},oa,w={},z=u.GoSquared,P,Q=u._gs||(P=!0,function(){ta.push(arguments)}),ta=Q.q||[];if(!Q.v){var R=function(a){A.apply({},a)};u._gs=A;A.v="6.7.1937";for(Q.q={push:R};Q=ta.shift();)R(Q);Ka();if(P){P=n.getElementsByTagName("script");
R=P.length;for(var ua;R--;)(ua=P[R].getAttribute("data-gs"))&&A(ua)}}})(window,document,navigator,setTimeout,clearTimeout,Date,encodeURIComponent);
